// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/messages.proto

package com.igal;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_igal_ProducerRecordMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_igal_ProducerRecordMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/protobuf/messages.proto\022\010com." +
      "igal\"[\n\025ProducerRecordMessage\022\013\n\003key\030\001 \001" +
      "(\014\022\r\n\005value\030\002 \001(\014\022\023\n\013target_type\030\003 \003(\t\022\021" +
      "\n\ttarget_id\030\004 \003(\tB\014\n\010com.igalP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_igal_ProducerRecordMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_igal_ProducerRecordMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_igal_ProducerRecordMessage_descriptor,
        new java.lang.String[] { "Key", "Value", "TargetType", "TargetId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
